completed string-manipulation-2
Victor-Park/c0322-code-solutions pull request #65
Opened 2022-04-26 09:45 UTC by Victor-Park

![Screen Shot 2022-04-26 at 2 44 13 AM](https://user-images.githubusercontent.com/99834589/165272332-2a78cd91-5dd6-44e4-829e-a7ad2f9bb74b.png)

2022-04-28 18:27 UTC, codingcodymiller requested changes

2022-04-28 18:27 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    return firstLetter.toUpperCase() + word.substring(1, 4).toLowerCase() + fifthLetter.toUpperCase() + word.substring(5).toLowerCase();
Since this is such a specific value, you don't need to construct it like this, you can just `return "JavaScript"

2022-04-28 18:27 UTC, codingcodymiller commented on string-manipulation-2/src/ransom-case.js
> +  } return splitString.join('');
Please always keep return statements on their own line.

2022-05-03 15:52 UTC, thebearingedge approved these changes

2022-05-03 18:29 UTC, merged